title: 'Info Bewerbungen'
data:
  title: Wohnungsbewerbungen
  text: 'Wir akzeptieren zur Zeit keine Bewerbungen. Wir werden an dieser Stelle informieren, sobald wir wieder neue Bewerbungen entgegennehmen können. Vielen Dank für Ihr Verständnis.'
  active: true
