tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              input_type: text
              antlers: false
              type: text
              display: Titel
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: text
            field:
              antlers: false
              type: textarea
              display: Text
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: active
            field:
              default: true
              type: toggle
              display: Aktivieren
              icon: toggle
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
